pipeline {
    agent any

    stages {
        stage('Dependencies'){
            steps{
                echo "Starting dependencies build"
                sh "cd jk"
                sh "docker build -f devopsDependencies.dockerfile --rm -t jenkins-dependencies ."
            }
            post{
                success{
                    sh 'echo "Built successfully!"' 
                }
                failure{
                    sh 'echo "Build failed!"'
                }
            }
        }
    }
}
