pipeline {
    agent any

    stages {
        stage('Dependencies'){
            steps{
                echo "Starting dependencies build"
                git url: 'https://github.com/yestraban/jenkinsRepo.git'
                sh "docker build -f devopsDependencies.dockerfile --rm -t jenkins-dependencies ."
            }
            post{
                success{
                    sh 'echo "Dependency build successfull!"' 
                }
                failure{
                    sh 'echo "Dependency build failed!"'
                }
            }
        }
        stage('Dependencies'){
            steps{
                echo "building app"
                //git url: 'https://github.com/yestraban/jenkinsRepo.git'
                sh "docker build -f devopsProjectBuild.dockerfile --rm -t jenkins-build ."
            }
            post{
                success{
                    sh 'echo "Built successfully!"' 
                }
                failure{
                    sh 'echo "Build failed!"'
                }
            }
        }
        stage('Tests'){
            steps{
                echo "building app"
                //git url: 'https://github.com/yestraban/jenkinsRepo.git'
                sh "docker build -f devopsProjectTest.dockerfile --rm -t jenkins-tests ."
            }
            post{
                success{
                    sh 'echo "Tests passed successfully!"' 
                }
                failure{
                    sh 'echo "Tests failed!"'
                }
            }
        }
    }
}
